services:
  backend:
    build: 
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - "ENVIRONMENT=development"
      - "DJANGO_SETTINGS_MODULE=conf.settings.local"
      - "DEBUG=1"
      - "DB_HOST=db"
    ports: 
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - ./backend/staticfiles:/usr/share/nginx/html/static/
      - ./backend/media:/usr/share/nginx/html/media/
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432" 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"

  frontend:
    build: 
      context: ./frontend
    environment:
      - "ENVIRONMENT=development"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app/frontend

volumes:
  postgres_data:
