services:
  backend:
    build: 
      context: ./backend
    command: gunicorn -c ./backend/services/gunicorn.config.py
    expose: 
      - "8000"
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - db
    environment:
      - "ENVIRONMENT=development"

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=${DB_USER:-postgres}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}"
      - "POSTGRES_DB=${DB_NAME:-postgres}"
    env_file:
      - "./backend/.env"

  frontend:
    build:
      context: ./frontend
    expose: 
      - "80"
    environment:
      - "VUE_APP_BACKEND_HOST=${BACKEND_HOST:-backend.samanznd.ir}"
    volumes:
      - ./frontend:/usr/src/app/frontend/

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERTS_DIR-/root/}:/etc/nginx/certs

volumes:
  postgres_data: