services:
  backend:
    restart: always
    build: 
      context: ./backend
    command: daphne -b 0.0.0.0 -p 8000 -e ssl:443:privateKey=/certs/private.key:certKey=/certs/cert.pem conf.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - ./backend/staticfiles:/usr/share/nginx/html/static/
      - ./backend/media:/usr/share/nginx/html/media/
      - /certs:/certs
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=${DB_USER:-postgres}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}"
      - "POSTGRES_DB=${DB_NAME:-postgres}"
    env_file:
      - "./backend/.env"

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/usr/share/nginx/html/static/
      - ./backend/media:/usr/share/nginx/html/media/
      - /certs:/certs
    depends_on:
      - backend

volumes:
  postgres_data:
