# Generated by Django 4.2.3 on 2023-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/thumbnails'),
            preserve_default=False,
        ),
    ]
