# Generated by Django 4.2.3 on 2023-08-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Content', max_length=30)),
                ('element_id', models.CharField(max_length=50)),
                ('parent_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contents', to='blog.content')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.content'),
        ),
    ]
