# Generated by Django 4.2.3 on 2023-08-04 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_content_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
    ]
