# Generated by Django 4.2.3 on 2023-08-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_article_content_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=30)),
                ('heading_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='heading',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='blog.article'),
        ),
        migrations.AddField(
            model_name='heading',
            name='parent_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='blog.heading'),
        ),
    ]
