# Generated by Django 4.2.3 on 2023-08-04 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_heading_remove_article_content_delete_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article',
            field=ckeditor.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
    ]
