# Generated by Django 4.2.3 on 2023-07-28 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='cv_images')),
                ('location', models.CharField(default='Mashhad', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('alt', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.image', to_field='uuid')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('explanations', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateField(default=datetime.date(2023, 7, 28))),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('images', models.ManyToManyField(through='cv.ImageProjectRelation', to='cv.image')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='technologies')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyProjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.technology', to_field='uuid')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(through='cv.TechnologyProjectRelation', to='cv.technology'),
        ),
        migrations.AddField(
            model_name='imageprojectrelation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.project'),
        ),
    ]
