# Generated by Django 4.2.3 on 2023-07-28 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
