# Generated by Django 4.2.3 on 2023-07-30 12:49

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_project_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='technologies', validators=[cv.models.image_validator]),
        ),
    ]
