# Generated by Django 4.2.3 on 2023-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_technology_options_alter_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
