# Generated by Django 4.2.3 on 2023-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name_plural': 'UserModel'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
