name: CI/CD ( Production )

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker-Compose Build 
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d

      - name: Stop Containers 
        run: docker-compose -f docker-compose.prod.yml down

      - name: Run Backend Tests 
        run: |
          docker-compose -f docker-compose.prod.yml up -d --no-deps db backend \
          && docker-compose -f docker-compose.prod.yml exec -T backend \
              python manage.py test --settings=conf.settings.production
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
