name: Docker-Compose

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker-Compose Build (Production)
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d \
            && docker-compose down

      - name: Run Backend Tests (Production)
        run: |
          docker-compose -f docker-compose.prod.yml up --no-deps db \
          && docker-compose -f docker-compose.prod.yml exec -T backend \
              python manage.py test --settings=conf.settings.production
