on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: isbang/compose-actions@v1.5.1
      - name: Building Images (Production)
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d
      - name: Running Backend Tests (Production)
        run: |
          docker-compose exec backend python manage.py test
