on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Building Images (Production)
        uses: isbang/compose-actions@v1.5.1
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d
      -
        name: Running Backend Tests (Production)
        uses: isbang/compose-actions@v1.5.1
        run: |
          docker-compose exec backend python manage.py test
